{
 "title": "Ads-Chair",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Show Ads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "show_ads", "legendFormat": "show_ads" }
   ]
  },
  {
   "title": "User Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "user_active", "legendFormat": "user_active" }
   ]
  },
  {
   "title": "Audio Moment Appropriate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "audio_moment_appropriate", "legendFormat": "audio_moment_appropriate" }
   ]
  },
  {
   "title": "Current Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "current_time", "legendFormat": "current time" }
   ]
  }
 ]
}